name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # This tells GitHub to pull your images correctly

      - name: Install Git LFS
        run: git lfs install

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # We add 'git lfs push' before the main push
        run: |
          git lfs push --all https://Kamazing:$HF_TOKEN@huggingface.co/spaces/Kamazing/MrMaower
          git push --force https://Kamazing:$HF_TOKEN@huggingface.co/spaces/Kamazing/MrMaower main
